[package]
name = "darkplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe        = "0.29.1"
egui          = "0.29.1"
egui_demo_lib = "0.29.1"
egui_glow     = "0.29.1"
libmpv2       = "4.1.0"
